name: starfive kernel

on:
  workflow_dispatch:
 

env:
  toolchain_tripe: riscv64-linux-gnu-
  ARCH: riscv

jobs:
  kernel:
    runs-on: ubuntu-22.04

    steps:
      - name: Install software
        run: |
              sudo apt update && \
              sudo apt install -y gdisk dosfstools gcc-riscv64-linux-gnu \
                                  libncurses-dev gawk flex bison openssl libssl-dev tree \
                                  dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf device-tree-compiler
                                  

      - name: Checkout kernel
        uses: actions/checkout@v3
        with:
            repository: 'starfive-tech/linux'
            ref: 'JH7110_VisionFive2_devel'
            path: 'linux/kernel'
            
      - name: Checkout opensbi
        uses: actions/checkout@v3
        with:
            repository: 'starfive-tech/opensbi'
            ref: 'master'
            path: 'linux/opensbi'
            
      - name: Checkout u-boot
        uses: actions/checkout@v3
        with:
            repository: 'starfive-tech/u-boot'
            ref: 'JH7110_VisionFive2_devel'
            path: 'linux/u-boot'
            
            
            
      - name: Compile Kernel && Install
        run: |
              tree -L 2 ${GITHUB_WORKSPACE}/linux/
              # pushd linux/kernel
                # make CROSS_COMPILE=${toolchain_tripe} ARCH=${ARCH} starfive_visionfive2_defconfig
                # make CROSS_COMPILE=${toolchain_tripe} ARCH=${ARCH} -j$(nproc) bindeb-pkg
              # popd
              pushd linux/u-boot
                make CROSS_COMPILE=${toolchain_tripe} ARCH=${ARCH} -j$(nproc)
              popd
