name: starfive kernel

on:
  workflow_dispatch:
 

env:
  toolchain_tripe: riscv64-linux-gnu-
  ARCH: riscv
  FW_PAYLOAD_PATH: ${GITHUB_WORKSPACE}/linux/u-boot/u-boot.bin
  FW_FDT_PATH: ${GITHUB_WORKSPACE}/linux/u-boot/arch/riscv/dts/starfive_visionfive2.dtb FW_TEXT_START=0x40000000
  

jobs:
  kernel:
    runs-on: ubuntu-22.04

    steps:
      - name: Install software
        run: |
              sudo apt update && \
              sudo apt install -y gdisk dosfstools gcc-riscv64-linux-gnu \
                                  libncurses-dev gawk flex bison openssl libssl-dev tree \
                                  dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf device-tree-compiler
                                  

      - name: Checkout kernel
        uses: actions/checkout@v3
        with:
            repository: 'starfive-tech/linux'
            ref: 'JH7110_VisionFive2_devel'
            path: 'linux/kernel'
            
      - name: Checkout opensbi
        uses: actions/checkout@v3
        with:
            repository: 'starfive-tech/opensbi'
            ref: 'master'
            path: 'linux/opensbi'
            
      - name: Checkout u-boot
        uses: actions/checkout@v3
        with:
            repository: 'starfive-tech/u-boot'
            ref: 'JH7110_VisionFive2_devel'
            path: 'linux/u-boot'
            
      - name: Checkout Tools
        uses: actions/checkout@v3
        with:
            repository: 'starfive-tech/Tools'
            ref: 'master'
            path: 'linux/Tools'
            
      - name: Build Tools
        run: |
              
              cd  ${GITHUB_WORKSPACE}/linux/Tools/spl_tool
              make
              tree -L 2 ${GITHUB_WORKSPACE}/linux/Tools/
              
      - name: Build u-boot
        run: |
              pushd linux/u-boot
                make CROSS_COMPILE=${toolchain_tripe} ARCH=${ARCH} starfive_visionfive2_defconfig
                make CROSS_COMPILE=${toolchain_tripe} ARCH=${ARCH} -j$(nproc)
              popd
              
      - name: Build opensbi
        run: |
              pushd linux/opensbi
                make PLATFORM=generic FW_PAYLOAD_PATH=${FW_PAYLOAD_PATH} FW_FDT_PATH=${FW_FDT_PATH}
              popd
              
      - name: Build Kernel
        run: |
              # pushd linux/kernel
                # make CROSS_COMPILE=${toolchain_tripe} ARCH=${ARCH} starfive_visionfive2_defconfig
                # make CROSS_COMPILE=${toolchain_tripe} ARCH=${ARCH} -j$(nproc) bindeb-pkg
              # popd
